### ISSUE TITLE
Find the duplicate in an array of N+1 integers.

### ISSUE THREAD

**Issue by sahushivam211** [sahushivam211/All-Standard-DSA-Problem-#10]
**Overview**

1. Write code  in C++.

2. Add that code into a directory named "Array", if the directory doesn't exist, create one and add the code file.

**Please take care of these things while creating the pull request.**

1. The code file was added to the correct directory.
2. Code quality looks good.
3. The programming language used is the same as mentioned in the issue.

**Comment by jaywyawhare** [comment]
Note: Please assign me for this issue

**Comment by CIC4DA** [comment]
Can I work on this issue.
