### ISSUE TITLE
2-Sum-Problem

### ISSUE THREAD

**Issue by sahushivam211** [sahushivam211/All-Standard-DSA-Problem-#12]
**Overview**

1. Write code for  in C++.

2. Add that code into a directory named "Array", if the directory doesn't exist, create one and add the code file.

**Please take care of these things while creating the pull request.**

1. The code file was added to the correct directory.
2. Code quality looks good.
3. The programming language used is the same as mentioned in the issue.

**Comment by SainathPoojary** [comment]
Hey @sahushivam211, I want to work on this please assign It to me.

**Comment by paras3624** [comment]
Hey! Can i work on this issue?
