### ISSUE TITLE
Merge Sort in c++

### ISSUE THREAD

**Issue by sahushivam211** [sahushivam211/All-Standard-DSA-Problem-#2]
**Overview**

1. Write code for Merge Sort in C++.

2. Add that code into a directory named "Sorting", if the directory doesn't exist, create one and add the code file.

**Please take care of these things while creating the pull request.**

1. The code file was added to the correct directory.
2. Code quality looks good.
3. The programming language used is the same as mentioned in the issue.

**Comment by 1-Sanchit-1** [comment]
can u please assign me

**Comment by shaneahmad** [comment]
Please assign me

**Comment by rishabhknowss** [comment]
Please assign me the task

**Comment by paras3624** [comment]
Hey! Can I work on this issue?

**Comment by raj-ravan** [comment]
please assign me this i will be able to do this
