### ISSUE TITLE
Reverse a LinkedList

### ISSUE THREAD

**Issue by sahushivam211** [sahushivam211/All-Standard-DSA-Problem-#20]
**Overview**

1. Write code for  in C++.

2. Add that code into a directory named "LinkedList", if the directory doesn't exist, create one and add the code file.

**Please take care of these things while creating the pull request.**

1. The code file was added to the correct directory.
2. Code quality looks good.
3. The programming language used is the same as mentioned in the issue.

**Comment by SubhashThenua** [comment]
@sahushivam211 Can you please assign this to me?.

Thanks!

**Comment by anjisnu07** [comment]
@sahushivam211 assign me for this

**Comment by Akash-1gif** [comment]
Hey @sahushivam211 I want to work on the following issue, please assign me this issue
