### ISSUE TITLE
Detect a cycle in Linked List

### ISSUE THREAD

**Issue by sahushivam211** [sahushivam211/All-Standard-DSA-Problem-#23]
**Overview**

1. Write code for  in C++.

2. Add that code into a directory named "LinkedList", if the directory doesn't exist, create one and add the code file.

**Please take care of these things while creating the pull request.**

1. The code file was added to the correct directory.
2. Code quality looks good.
3. The programming language used is the same as mentioned in the issue.

**Comment by REX-HERE** [comment]
please assign this to me
