### ISSUE TITLE
Quick Sort in JAVA

### ISSUE THREAD

**Issue by sahushivam211** [sahushivam211/All-Standard-DSA-Problem-#3]
**Overview**

1. Write code for Quick Sort in JAVA.

2. Add that code into a directory named "Sorting", if the directory doesn't exist, create one and add the code file.

**Please take care of these things while creating the pull request.**

1. The code file was added to the correct directory.
2. Code quality looks good.
3. The programming language used is the same as mentioned in the issue.

**Comment by rishabhknowss** [comment]
please assign me the task

**Comment by JayantVashishtha** [comment]
I would love to contribute in the task.

**Comment by raj-ravan** [comment]
please assign me this i will be able to do this.......
